import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container:{
        padding:40,
        backgroundColor:'#ffffff',
        justifyContent:'center',
        alignItems:'center',
        height:'100%'
    },
    backg:{
        backgroundColor:'#495B63',
        borderRadius:20,
        margin:5,
        padding:20
    },
    boldT:{
        fontSize:20,
        fontWeight:'bold',
        textAlign:'center'
    },
    boldTT:{
        marginTop:20,
        fontSize:20,
        fontWeight:'bold',
        textAlign:'center'
    },
    img:{
        width:200,
        height:200,
        resizeMode:'cover',
        margin:20
    },
    sr:{
        backgroundColor:'#1F4150',
        borderRadius:20,
        marginTop:20
    },
    ttext:{
        textAlign:'center',
        fontSize:16,
        color:'white',
        paddingLeft:40,
        paddingRight:40,
        paddingTop:5,
        paddingBottom:5
    },
    text:{
        textAlign:'center',
        fontSize:16,
        color:'white',
        height:'20%',
    },
    mem:{
        fontStyle:'italic',
        fontSize:16,
        color:'white',
        marginTop:30,
        textAlign:'center'
    },
    time:{
        fontSize:17,
        color:'#1DA1F2',
        fontWeight:'bold',
        margin:10
    },
    item:{
        padding:20,
        height:200,
    }
})